# Generated by Django 4.2.3 on 2024-01-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_type', models.CharField(max_length=100)),
                ('response_answers', models.JSONField()),
                ('response_results', models.JSONField()),
                ('response_date', models.DateField()),
                ('response_time', models.TimeField()),
                ('response_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
