name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  # Cancels previous run based on a unique workflow+pull request number, or branchname
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check JSON schema
        run: |
          python3 validate_schema.py all
      - name: Run linter
        run: |
          pre-commit run --all-files